### ISSUE TITLE
No such file or directory: writefile '.deno_webui/a6acdc45-webui-macos-clang-arm64/webui-2.dylib'

### ISSUE THREAD

**Issue by jeff-hykin** [webui-dev/deno-webui#17]
> However, the actual Deno repo uses an old Beta 2.4. You don't need to build anything, just clone the Deno repo and run it. If you get any issues, please feel free to open a new issue and share details and logs as possible.

<img width="619" alt="Screen Shot 2023-11-01 at 8 43 04 AM" src="https://github.com/webui-dev/deno-webui/assets/17692058/bf9a04c7-6ff5-414b-97e4-ec6eab6e18c5">

**Comment by jeff-hykin** [comment]
After making this little change:
<img width="1373" alt="Screen Shot 2023-11-01 at 9 53 02 AM" src="https://github.com/webui-dev/deno-webui/assets/17692058/b332f79a-b84c-4edc-a77a-640d789514de">


 I get:

```
Uncaught Error: Could not open library:
dlopen(/Users/jeffhykin/.deno_webui/a6acdc45-webui-macos-clang-arm64/webui-2.dylib, 0x0005):
tried: '/Users/jeffhykin/.deno_webui/a6acdc45-webui-macos-clang-arm64/webui-2.dylib' (not a mach-o file)
    at new DynamicLibrary (ext:deno_ffi/00_ffi.js:440:46)
    at Object.dlopen (ext:deno_ffi/00_ffi.js:577:10)
    at loadLib (file:///Users/jeffhykin/repos/deno-webui//src/lib.ts:119:15)
    at new WebUI (file:///Users/jeffhykin/repos/deno-webui//src/webui.ts:54:47)
    at <anonymous>:3:16
```

**Comment by jeff-hykin** [comment]
Manually replacing the dylib with the debugging one gets past this issue and opens up a UI window

**Comment by redradist** [comment]
@jeff-hykin I have the similar issue (https://github.com/webui-dev/deno-webui/issues/28)
Any suggestions how to solve it ?

**Comment by jeff-hykin** [comment]
yep! Just use my fork @redradist I bundled all of them.
https://github.com/jeff-hykin/deno-webui

**Comment by redradist** [comment]
> yep! Just use my fork @redradist I bundled all of them for every OS. https://github.com/jeff-hykin/deno-webui
> 
> There's some quirks like it shows the top bar (which I think is another issue for webui main repo), but it at least runs.

@jeff-hykin Why not create PR in this repo ??

**Comment by AlbertShown** [comment]
The last commits actually solved the issue very well in Windows, I tested it.
We can use `bootstrap.bat` to download all binaries, or `bootstrap.bat minimal` to download only the actual OS one binary file, or we can completely skip bootstrap step and let deno-webui download the needed binary at every runtime.

However, it works well on Windows, on macOS Deno creates the `x` folder to download the modules, so the path should be `./x/` but right now deno-webui use it as `/x/` (it misses the dot) which it won't work.

**Comment by jeff-hykin** [comment]
Oops I actually gave you the wrong link @redradist. My working version is on the master (not main) branch of my fork:
https://github.com/jeff-hykin/deno-webui/tree/master

I'm going to go ahead an edit my earlier comment

**Comment by AlbertShown** [comment]
I tested [v2.4.3](https://github.com/webui-dev/deno-webui/releases/tag/2.4.3) in Windows and Linux, and it's working fine. Can someone please test it in macOS?
2.4.3 should fix those binary issues.

**Comment by redradist** [comment]
> I tested [v2.4.3](https://github.com/webui-dev/deno-webui/releases/tag/2.4.3) in Windows and Linux, and it's working fine. Can someone please test it in macOS? 2.4.3 should fix those binary issues.

@AlbertShown Yes, not it is working on MacOS !! Thanks !!

**Comment by jeff-hykin** [comment]
Also works for me now, thanks @AlbertShown 👍
