### ISSUE TITLE
WebUI initially works then falls over

### ISSUE THREAD

**Issue by binarytide** [webui-dev/deno-webui#46]
os is macOS Sonoma

main.js
```
import { WebUI } from 'https://deno.land/x/webui/mod.ts'

const myWindow = new WebUI()
myWindow.setRootFolder('./dist')
myWindow.show('index.html')
await WebUI.wait()
```

task:
`"testWeb": "deno run --log-level=debug --unstable-ffi --allow-all api/main.js dist/"`

<img width="426" alt="image" src="https://github.com/webui-dev/deno-webui/assets/899298/4e1a4bbf-d60e-4d5d-ba54-8cd771aff936">

<img width="659" alt="image" src="https://github.com/webui-dev/deno-webui/assets/899298/0bd8280e-b813-44e8-97e0-d6dd85f0667d">

output:
```➜  deno-vite git:(main) ✗ deno task testWeb
Task testWeb deno run --log-level=debug --unstable-ffi --allow-all api/main.js dist/
DEBUG RS - deno_config:685 - Config file found at '/path-to-project/deno-vite/deno.json'
DEBUG RS - deno::args::package_json:146 - No package.json file found
DEBUG RS - deno::cache::cache_db:131 - Opening cache /Users/userfolder/Library/Caches/deno/dep_analysis_cache_v1...
DEBUG RS - deno::cache::cache_db:131 - Opening cache /Users/userfolder/Library/Caches/deno/node_analysis_cache_v1...
DEBUG RS - deno::js:10 - Deno isolate init with snapshots.
DEBUG RS - deno::worker:171 - main_module file:///path-to-project/deno-vite/api/main.js
DEBUG RS - deno::module_loader:104 - Preparing module load.
DEBUG RS - deno::module_loader:108 - Creating module graph.
DEBUG RS - deno::args:1393 - Deno config was not a package: Missing 'name' field in config file.
DEBUG RS - deno::file_fetcher:529 - FileFetcher::fetch() - specifier: file:///path-to-project/deno-vite/api/main.js
DEBUG RS - deno::file_fetcher:529 - FileFetcher::fetch() - specifier: https://deno.land/x/webui@2.4.4/mod.ts
DEBUG RS - deno::file_fetcher:297 - FileFetcher::fetch_remote() - specifier: https://deno.land/x/webui@2.4.4/mod.ts
DEBUG RS - deno::file_fetcher:208 - FileFetcher::fetch_cached - specifier: https://deno.land/x/webui@2.4.4/mod.ts
DEBUG RS - deno::file_fetcher:529 - FileFetcher::fetch() - specifier: https://deno.land/x/webui@2.4.4/src/webui.ts
DEBUG RS - deno::file_fetcher:297 - FileFetcher::fetch_remote() - specifier: https://deno.land/x/webui@2.4.4/src/webui.ts
DEBUG RS - deno::file_fetcher:208 - FileFetcher::fetch_cached - specifier: https://deno.land/x/webui@2.4.4/src/webui.ts
DEBUG RS - deno::file_fetcher:529 - FileFetcher::fetch() - specifier: https://deno.land/x/webui@2.4.4/src/lib.ts
DEBUG RS - deno::file_fetcher:297 - FileFetcher::fetch_remote() - specifier: https://deno.land/x/webui@2.4.4/src/lib.ts
DEBUG RS - deno::file_fetcher:208 - FileFetcher::fetch_cached - specifier: https://deno.land/x/webui@2.4.4/src/lib.ts
DEBUG RS - deno::file_fetcher:529 - FileFetcher::fetch() - specifier: https://deno.land/x/webui@2.4.4/src/types.ts
DEBUG RS - deno::file_fetcher:297 - FileFetcher::fetch_remote() - specifier: https://deno.land/x/webui@2.4.4/src/types.ts
DEBUG RS - deno::file_fetcher:208 - FileFetcher::fetch_cached - specifier: https://deno.land/x/webui@2.4.4/src/types.ts
DEBUG RS - deno::file_fetcher:529 - FileFetcher::fetch() - specifier: https://deno.land/x/webui@2.4.4/src/utils.ts
DEBUG RS - deno::file_fetcher:297 - FileFetcher::fetch_remote() - specifier: https://deno.land/x/webui@2.4.4/src/utils.ts
DEBUG RS - deno::file_fetcher:208 - FileFetcher::fetch_cached - specifier: https://deno.land/x/webui@2.4.4/src/utils.ts
DEBUG RS - deno::file_fetcher:529 - FileFetcher::fetch() - specifier: https://deno.land/x/webui@2.4.4/deps.ts
DEBUG RS - deno::file_fetcher:297 - FileFetcher::fetch_remote() - specifier: https://deno.land/x/webui@2.4.4/deps.ts
DEBUG RS - deno::file_fetcher:208 - FileFetcher::fetch_cached - specifier: https://deno.land/x/webui@2.4.4/deps.ts
DEBUG RS - deno::npm::managed::resolution:313 - Snapshot already up to date. Skipping pending npm resolution.
DEBUG RS - deno::module_loader:164 - Prepared module load.
process id 0
error: Uncaught (in promise) Error: unable to start the browser
      throw new WebUIError(`unable to start the browser`);
            ^
    at WebUI.show (https://deno.land/x/webui@2.4.4/src/webui.ts:106:13)
    at file:///path-to-project/deno-vite/api/main.js:47:10
    at eventLoopTick (ext:core/01_core.js:168:7)
➜  deno-vite git:(main) ✗ 
```

initially I get a new chrome window with expected vue application, but refreshing the page says site cannot be reached and it seems to disconnect and timeout with log stating 'unable to start the browser'

**Comment by binarytide** [comment]
that looks like it was the issue, is there an example of including webui on the front end within a js/vue project? I added the script to the built project but would prefer to import properly
