### ISSUE TITLE
[bug] deno-webui crashes if you open a window after closing all windows

### ISSUE THREAD

**Issue by Drakim** [webui-dev/deno-webui#66]
If at any point you close all windows spawned by deno-webui, you will be unable to spawn any new windows as deno will crash from an uncaught error:

```
error: Uncaught (in promise) Error: unable to start the browser
      throw new WebUIError(`unable to start the browser`);
            ^
    at WebUI.show (https://deno.land/x/webui@2.5.0/src/webui.ts:105:13)
    at file:///.../deno-webui/examples/hello_world/hello_world.ts:125:10
    at eventLoopTick (ext:core/01_core.js:214:9)
```

To see this bug in action, simply modify the hello_world.ts example so that it works like this:

```ts
// Show the window
myWindow.show(myHtml); // Or myWindow.show('./myFile.html');

// Wait until all windows get closed
await WebUI.wait();

console.log("Thank you.");

// Show the window again
myWindow.show(myHtml); // Crash here!

// Wait until all windows get closed again
await WebUI.wait();
```

**Comment by Drakim** [comment]
Success!

Jumping to that commit id and testing with your code appended to the hello_world.ts example I get new windows after closing the previous one and no errors!

Thank you for the incredibly fast response. 👌

**Comment by Drakim** [comment]
Oh, but you typed setMultiClient's parameter as `Boolean`, you problaby want to type it as `boolean`

**Comment by Drakim** [comment]
Huh... it appears that by using `WebUI.setMultiClient(true)` then the `script()` method of WebUI instances stops working, and in a very odd way, it simply rejects() it's promise, and the reject value is an empty string, no proper error message.

**Comment by Drakim** [comment]
I understand, thank you for the explanation. Meanwhile I can live without `setMultiClient(true)` while developing 🙂

**Comment by Drakim** [comment]
Thank you,

However, something appears to have gone wrong. The example you gave above showing ```WebUI.setMultiClient(true);``` no longer appears to work with this Deno-WebUI v2.5.1 release. When I try to run it I am back to getting this error when opening the second window:
```
C:\...\deno-webui\examples\hello_world>deno --allow-all hello_world.ts
allEvents: window = [object Object]
allEvents: eventType = 1
allEvents: element =
allEvents: window = [object Object]
allEvents: eventType = 0
allEvents: element =
Window closed, open it again...
error: Uncaught (in promise) Error: unable to start the browser
      throw new WebUIError(`unable to start the browser`);
            ^
    at WebUI.show (https://deno.land/x/webui@2.5.1/src/webui.ts:100:13)
    at allEvents (file:///D:/sync/repo/deno-webui/examples/hello_world/hello_world.ts:36:14)
    at https://deno.land/x/webui@2.5.1/src/webui.ts:406:39
```

**Comment by Drakim** [comment]
Makes sense, thanks for the explanation. 🙂

**Comment by Drakim** [comment]
Aha, good catch. I will do so.

But this could potentially confuse future users of WebUI who don't know to insert the setTimeout(). Isn't there a way to sorta see if firefox is busy and build the delay into the library? Or abort the request and try again if it fails a couple of times?

Either way, I know enough to work my way around the problem, thank you very much for investigating the issue.

**Comment by DevRubicate** [comment]
Hm, makes sense.

**Comment by DevRubicate** [comment]
I've been testing a bunch, and here is what I've discovered:

1. Using `WebUI.setMultiClient(true);` and the `scriptClient()` method does work neatly, so I can now open multiple windows, close them, and communicate with messages, this is good. It's a bit odd that I have to save an Event object as my main anchor of message communication instead of the actual constructed WebUI instance representing that window but it's no big deal. 😁

2. Both firefox and chrome will produce the "unable to start the browser" occasionally, with firefox doing it a lot more frequently. I added in a setTimeout as you suggested, and that seems to help, however, it's not an exact science. Sometimes 1000ms is enough, sometimes it's not enough. To be safe I have to arbitrarily pad up all my user actions to always take two seconds to respond each click, this is a very sad user experience. 😟

3. Sometimes the "unable to start the browser" error comes up even when there has been 10+ seconds between closing the last window and opening a new one. I assume it's based on external factors what's going on in the PC. Maybe sometimes the browser closes slower because it plans on applying an automatic update like modern browsers like to do. It's probably not your fault but WebUI suffers greatly as a tool because of it. 😟

4. When the "unable to start the browser" error happens it always crashes my entire Deno app, it doesn't matter if I have a `try catch` around any of the WebUI functions I call. This means using WebUI is akin to playing Russian Roulette, any time I open a window it means my app may crash. This is a very sad user experience. 😟

I understand WebUI is still heavily under development, and that nobody can expect a perfectly stable product this early in development (WebUI website does say "In development...." for most things under Deno).

But these issues will be blockers for anybody wishing to try the library even for a trivial case. I've been happy to help out finding out issues and problems so far, but I will either have to pause my own project until WebUI is more mature or switch to some other library. I can't even show off my project as a prototype to somebody if clicks takes several seconds to apply and the app randomly crashes. 🥲

**Comment by DevRubicate** [comment]
1. Oh, I see. So "window" refers to one instance of the browser. while "client" refers to one actual open viewport? The termonology is a bit confusing because to laypeople they would call the client a window.

3. Understood, and as I said, this is not WebUI's fault. It's just unfortunate that WebUI comes off as difficult and unstable to use due to browser problems, but such is life.

4. No, `try{} catch (error) {}` does not help, Deno will still crash. I assume this is because some async scope issue means that the error does not happen in the scope of the caller.
